sudo: required
dist: trusty
language: julia

os:
  - linux

julia:
  - 0.4
  - 0.5
  - nightly

python:
  - "2.7"

compiler: gcc

install:
  - sudo apt-get update
  - sudo pip install cython
  - sudo pip install numpy pandas
  - sudo pip install feather-format
  - sudo pip install feather-format --upgrade

notifications:
  email: false

after_success:
  - julia -e 'cd(Pkg.dir("Feather")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("Feather")); include(joinpath("docs", "make.jl"))'
