language: julia

os:
  - linux
  - osx

julia:
  - 0.4
  - 0.5
  - nightly

python:
  - "3.5"

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda install numpy pandas
  - conda install feather-format -c conda-forge

notifications:
  email: false

after_success:
  - julia -e 'cd(Pkg.dir("Feather")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("Feather")); include(joinpath("docs", "make.jl"))'
