language: julia

os:
  - linux
  - osx

julia:
  - 0.4
  - 0.5
  - nightly

python:
  - "3.5"

install:
  - sudo apt-get install -y libffi-dev libssl-dev
  - sudo pip install requests[security]
  - sudo pip install numpy
  - sudo pip install pandas
  - sudo pip install feather-format

notifications:
  email: false

after_success:
  - julia -e 'cd(Pkg.dir("Feather")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("Feather")); include(joinpath("docs", "make.jl"))'
